import {
  ExecutionExerciseEnum,
  ExerciseTargetMuscle,
  ExerciseType,
  IExercisesTree,
} from 'src/types/ExerciseTypes'

// man video
const pushUpVid = require('src/assets/videos/ex/push-up.mp4')

// woman video

const generateExerciseTree = (): IExercisesTree => {
  return {
    man: [
      // base
      {
        id: 0,
        name: 'Push ups',
        video: pushUpVid,
        execution: ExecutionExerciseEnum.REPEAT,
        targetMuscles: [ExerciseTargetMuscle.TRICEPS, ExerciseTargetMuscle.CHEST],
        needInventar: null,
        type: ExerciseType.PUSH,
        coefficientDifficult: 1,
        awailableForPercent: 0,
        max: 200,
      },
      {
        id: 1,
        name: 'Sit ups',
        video: pushUpVid,
        execution: ExecutionExerciseEnum.REPEAT,
        targetMuscles: [ExerciseTargetMuscle.BUTT, ExerciseTargetMuscle.HIPS],
        needInventar: null,
        type: ExerciseType.LEGS,
        coefficientDifficult: 1,
        awailableForPercent: 0,
        max: 500,
      },
      {
        id: 2,
        name: 'Plank',
        video: pushUpVid,
        execution: ExecutionExerciseEnum.HOLD,
        targetMuscles: [ExerciseTargetMuscle.CORE],
        needInventar: null,
        type: ExerciseType.CORE,
        coefficientDifficult: 1,
        awailableForPercent: 0,
        max: 1800,
      },
      // push
      {
        id: 3,
        name: 'Narrow push ups',
        video: pushUpVid,
        execution: ExecutionExerciseEnum.REPEAT,
        targetMuscles: [ExerciseTargetMuscle.TRICEPS, ExerciseTargetMuscle.CHEST],
        needInventar: null,
        type: ExerciseType.PUSH,
        coefficientDifficult: 0.7,
        awailableForPercent: 0,
      },
      {
        id: 4,
        name: 'Wide push ups',
        video: pushUpVid,
        execution: ExecutionExerciseEnum.REPEAT,
        targetMuscles: [ExerciseTargetMuscle.TRICEPS, ExerciseTargetMuscle.CHEST],
        needInventar: null,
        type: ExerciseType.PUSH,
        coefficientDifficult: 1,
        awailableForPercent: 0,
      },
      {
        id: 5,
        name: 'Bowman push ups',
        video: pushUpVid,
        execution: ExecutionExerciseEnum.REPEAT,
        targetMuscles: [ExerciseTargetMuscle.TRICEPS, ExerciseTargetMuscle.CHEST],
        needInventar: null,
        type: ExerciseType.PUSH,
        coefficientDifficult: 0.7,
        awailableForPercent: 10,
      },
      {
        id: 6,
        name: 'France push ups',
        video: pushUpVid,
        execution: ExecutionExerciseEnum.REPEAT,
        targetMuscles: [ExerciseTargetMuscle.TRICEPS, ExerciseTargetMuscle.CHEST],
        needInventar: null,
        type: ExerciseType.PUSH,
        coefficientDifficult: 0.6,
        awailableForPercent: 10,
      },
      {
        id: 7,
        name: 'France push ups with jumping',
        video: pushUpVid,
        execution: ExecutionExerciseEnum.REPEAT,
        targetMuscles: [ExerciseTargetMuscle.TRICEPS, ExerciseTargetMuscle.CHEST],
        needInventar: null,
        type: ExerciseType.PUSH,
        coefficientDifficult: 0.6,
        awailableForPercent: 20,
      },
      {
        id: 8,
        name: 'Mismatch push ups with jumping',
        video: pushUpVid,
        execution: ExecutionExerciseEnum.REPEAT,
        targetMuscles: [ExerciseTargetMuscle.TRICEPS, ExerciseTargetMuscle.CHEST],
        needInventar: null,
        type: ExerciseType.PUSH,
        coefficientDifficult: 0.6,
        awailableForPercent: 20,
      },
    ],
    woman: [
      {
        id: 0,
        name: 'Push ups',
        video: pushUpVid,
        execution: ExecutionExerciseEnum.REPEAT,
        targetMuscles: [ExerciseTargetMuscle.TRICEPS, ExerciseTargetMuscle.CHEST],
        needInventar: null,
        type: ExerciseType.PUSH,
        coefficientDifficult: 1,
        awailableForPercent: 0,
        max: 100,
      },
      {
        id: 1,
        name: 'Sit ups',
        video: pushUpVid,
        execution: ExecutionExerciseEnum.REPEAT,
        targetMuscles: [ExerciseTargetMuscle.BUTT, ExerciseTargetMuscle.HIPS],
        needInventar: null,
        type: ExerciseType.LEGS,
        coefficientDifficult: 1,
        awailableForPercent: 0,
        max: 300,
      },
      {
        id: 2,
        name: 'Plank',
        video: pushUpVid,
        execution: ExecutionExerciseEnum.HOLD,
        targetMuscles: [ExerciseTargetMuscle.CORE],
        needInventar: null,
        type: ExerciseType.CORE,
        coefficientDifficult: 1,
        awailableForPercent: 0,
        max: 1200,
      },
    ],
  }
}

export default generateExerciseTree
